### PR TITLE
making thumbnails update

### PR DESCRIPTION
**Pull request by gvn**
Not sure if this is terrible, but it seems to work.

### CODE REVIEW

**Comment by gvn** [comment]
Closes #1982

**Comment by thisandagain** [comment]
I'm still able to reproduce the updating issue, but also seems to cause or amplify another issue in which if I add multiple items it starts to get into a strange loop in which new elements won't be displayed or update. Perhaps a race condition or even an issue where we are using brittle IDs or assigning properties to the wrong element? At the very end of the screen recording you'll notice that a text element just disappears (I did not delete it). Screen recording: https://www.dropbox.com/s/vapc2kysvoid36w/bug.mp4?dl=0

**Comment by thisandagain** [comment]
Landing this as an incremental improvement. Updating #1982 with details.

**Pull request merged**
