### PR TITLE
replacing default thumbs

### LINKED ISSUE #2099: Swap placeholder project thumb
Replace the gradient thumbnail in discover/make to be used when the real thumb is not yet generated or is broken. See the bottom of #2020.

### PR DESCRIPTION
**Pull request by gvn**
Fixes #2099 

Note: I tried to optimize the SVG, but the result didn't render properly...so... `¯\_(ツ)_/¯`

### CODE REVIEW

**Comment by thisandagain** [comment]
@k88hudson R?

**Comment by k88hudson** [comment]
I'm seeing this for the top two projects in discovery:

image

**Comment by gvn** [comment]
Ok, this should fix the missing ones...

**Comment by k88hudson** [comment]
Sweet i'll take another look

**Comment by k88hudson** [comment]
R+!

**Pull request merged**
