### PR TITLE
[#2134] Launch tinker mode even if no edits were made yet

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by k88hudson** [comment]
@thisandagain R?

**Comment by thisandagain** [comment]
Only issue I'm seeing is that the "Transparency" slider is set to `1` when you enter Tinker Mode (I'm testing border color on an image) even though the value shown is `0`. From a user experience perspective, I'm wondering if we should keep the default as one and update the state. Without that the color selector feels broken even though the user intent is most likely to pick a color. Make sense? Thoughts?

**Comment by k88hudson** [comment]
@thisandagain good catch! this was actually a bug in our `Range` component

**Comment by thisandagain** [comment]
W00t! Thanks for the quick fix. R+

**Pull request merged**
