### PR TITLE
Add gorgeous new logo to login :)

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by k88hudson** [comment]
@vazquez I adjusted the spacing a little so the Join text at the bottom doesn't get cut off (on a nexus 4 at least), what do you think?

screenshot_2015-06-12-18-21-03

**Comment by xmatthewx** [comment]
Beautiful. (And yes, join bit was always a little too tight against the bottom of the screen)

**Comment by vazquez** [comment]
Perfect, it's better to show the CTA. :+1:

On Friday, June 12, 2015, Kate Hudson <notifications@github.com> wrote:

> @vazquez <https://github.com/vazquez> I adjusted the spacing a little so
> the Join text at the bottom doesn't get cut off (on a nexus 4 at least),
> what do you think?
>
> [image: screenshot_2015-06-12-18-21-03]
> <https://cloud.githubusercontent.com/assets/1455535/8141075/2814cda0-1130-11e5-951e-f5c00ceccff1.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-android/pull/2203#issuecomment-111632585>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by gvn** [comment]
Might want to run `svgo` on the SVG, but otherwise LGTM!

**Pull request merged**
