### PR TITLE
Changing header strings.

### PR DESCRIPTION
**Pull request by vazquez**
Fixes https://github.com/mozilla/webmaker-core/issues/594
Fixes https://github.com/mozilla/webmaker-core/issues/872
Fixes https://github.com/mozilla/webmaker-core/issues/834
Fixes https://github.com/mozilla/webmaker-core/issues/835

### CODE REVIEW

**Comment by alanmoo** [comment]
This looks good to me, and shows up in the compile project nicely. @gvn is there anything I might be missing?

**Comment by gvn** [comment]
Should be fine since it's just updating strings and not adding new keys.

@alicoding – Should this go to Transifex?

**Comment by alicoding** [comment]
Yup you will also need to upload the file on transifex

**Comment by xmatthewx** [comment]
Tracking localization here: https://github.com/mozilla/webmaker-core/issues/871

**Pull request merged**
