### PR TITLE
Button label editing

### PR DESCRIPTION
**Pull request by Pomax**
swaps a label for an input element for native text input while editing.

### CODE REVIEW

**Comment by flukeout** [comment]
@Pomax 

**Done button bug**
* Edit the button label
* Don't finish editing, but hit the back arrow until you are in the map view
* Edit the button again
* "Edit Text" button will still say "Done" - it should say "Edit Text"

Note: we have an issue to get rid of the "Done" button altogether, so might not be worth fixing. Maybe we just kill it off?


**Other Feedback**
* "Edit Text" should read "Edit Label"
* When I edit the label, the caret should be placed at the end of the text, not at the beginning
* Unlike the Text Element, if I tap the Button in the preview, I don't get to edit the text, can we add tap-to-edit behaviour to keep it consistent?

**Comment by Pomax** [comment]
let's go will killing the button back off, then.
1. kk
2. are you sure? as an HTML element, this is the default behaviour. 
3. yeah that's odd, it should not handle the tap as a button press, but instead handle it as a text activation.

**Comment by Pomax** [comment]
All the things should be addressed now, except for the button's existence

**Comment by flukeout** [comment]
@Pomax 

A bug:
* Add a button
* Edit the label
* When editing place the caret in the middle of a word
* type a character
* caret jumps to the end of the label

**Comment by Pomax** [comment]
all thee bugs should be gone

**Comment by flukeout** [comment]
**Space bug**
* If you add spaces at the end of your label
* If you use the "Done" keyboard key or tap away from the field, they are trimmed
* If you tap the "Back" arrow, the spaces remain in the label

They should go away.

**Comment by Pomax** [comment]
this seems to be an issue related to Android swapping out the view without the neccessary events triggering first (like the `onblur` event). @thisandagain might know how we can hook into that for some more flexibility.

The reason we can't `trim()` on every keystroke is that if we did, you'd never be able to type a sentence, so this is a really interesting bug that might not have a good solution for it without making Android hook into the view to say "yo, you're getting swapped out, do what you need to do right now and then I'm caching your state and getting rid of you"

**Comment by flukeout** [comment]
Server side text trimming (as a service)

**Comment by Pomax** [comment]
passing it over to @k88hudson for a code review before merging

**Comment by thisandagain** [comment]
This is excellent. Thanks @Pomax and @flukeout ! R+

**Pull request merged**
