### PR TITLE
Setup for API handling on the java side

### PR DESCRIPTION
**Pull request by Pomax**
Works in conjunction with https://github.com/mozilla/webmaker-core/pull/327 - the code work towards satisfying https://github.com/mozilla/webmaker-core/issues/261 and https://github.com/mozilla/webmaker-core/issues/183

### CODE REVIEW

**Comment by thisandagain** [comment]
R+ :sunglasses:

**Comment by Pomax** [comment]
rebased prior to merging.

**Comment by Pomax** [comment]
let's not close, but just merge... =_=

**Comment by ryanw-se** [comment]
@Pomax Great work :D

**Pull request merged**
