### PR TITLE
google play string yml file for transifex

### PR DESCRIPTION
**Pull request by secretrobotron**
So we can upload to transifex, and simply copy & paste into play store when necessary.

Provides strings for https://github.com/mozilla/webmaker-core/issues/289

### CODE REVIEW

**Comment by secretrobotron** [comment]
@alicoding r?

**Comment by secretrobotron** [comment]
cc @thisandagain

**Comment by secretrobotron** [comment]
After R+, I'll upload to transifex.

**Comment by alicoding** [comment]
R+

**Pull request merged**
