### PR TITLE
Build configuration fixes

### PR DESCRIPTION
**Pull request by thisandagain**
Should resolve issues for x86-based emulators

### CODE REVIEW

**Comment by k88hudson** [comment]
I don't see that error anymore. I had to build a couple of times before it worked (I got `Session 'app': error` with no other output) but might have been an unrelated issue.

Tested on an x86 emulator/API 21/5.0.1

**Comment by thisandagain** [comment]
Generally when the build config changes it's a good idea to clean the project. That might have been what caused that particular error.

**Comment by k88hudson** [comment]
@thisandagain I did, but who knows ^_^

**Comment by thisandagain** [comment]
Gah. Let me know if you see it again. Thanks @k88hudson

**Pull request merged**
