### PR TITLE
[#2066] Refresh make view with updates

### PR DESCRIPTION
**Pull request by k88hudson**
This refreshes after pause, resume, and changes in which tab is active -- do you think that's too often?

### CODE REVIEW

**Comment by k88hudson** [comment]
@thisandagain R? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by thisandagain** [comment]
On tab selected is too frequently (particularly when we have pull-to-refresh). Remove that and I think this is good to go.

**Comment by k88hudson** [comment]
@thisandagain is this ok?

**Comment by thisandagain** [comment]
Working well! R+

**Pull request merged**
