### PR TITLE
revert patch for the panzoom PR

### PR DESCRIPTION
**Pull request by Pomax**
The panzoom PR #1998 introduced a bug that prevented the app from operating as expected, with investigations listed in #2009 - I tried several work-arounds, but these seemed to merely move the bug around rather than fixing it, so ultimate the safest way forward is to back out the PR, refile it, and do a bit more testing on it before we merge it in a second time.

Revert procedure used:
```
$> git fetch mozilla
$> git checkout -B develop mozilla/develop
$> git revert 35b21d2ba81e7d911081f643e98425ca7a8a8c7b -m 1
```
with `-m 1` indicating that the revert parent was https://github.com/mozilla/webmaker-android/commit/88ddfe92c68404ac7435b859b6fab3ffb5bb46c3

This left a single merge conflict in router.jsx, over whether the parameters var was `r` or `params`, which was a trivial merge fix.

### CODE REVIEW

**Comment by errietta** [comment]
wfm

**Comment by thisandagain** [comment]
Working for me as well. Just testing on a few different devices... will ping once complete.

**Comment by thisandagain** [comment]
Cool. This is working well across devices. The only blocker I'm seeing is on a fresh install the first project you go to I cannot pan or zoom. Backing out and going to any other project seems to resolve the issue.

**Comment by thisandagain** [comment]
Console:
```bash
I/chromium(22140): [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token u", source: file:///android_asset/www/pages/project/index.html (1)
I/chromium(22140): [INFO:CONSOLE(2216)] "Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Project. See http://fb.me/react-warning-keys for more information.", source: file:///android_asset/www/js/project.bundle.js (2216)
I/chromium(22140): [INFO:CONSOLE(2216)] "Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of ElementGroup. See http://fb.me/react-warning-keys for more information.", source: file:///android_asset/www/js/project.bundle.js (2216)
```

**Comment by thisandagain** [comment]
Ok. I think I have this tracked down to line `91` of `project.jsx`:
```js
var state = JSON.parse(window.Android.getMemStorage('state'));
```

**Comment by thisandagain** [comment]
R+. Issue not related to this patch. Will follow-up.

**Comment by Pomax** [comment]
Original bug: https://github.com/mozilla/webmaker-android/issues/1697

**Pull request merged**
