### PR TITLE
Enable user projects view

### PR DESCRIPTION
**Pull request by alanmoo**
Requires https://github.com/mozilla/webmaker-core/pull/766 to be closed first. Please take a good look at this because for the most part

noidea-professor

### CODE REVIEW

**Comment by alanmoo** [comment]
@ryanw-se Maybe you could take a look at this too?

**Comment by ryanw-se** [comment]
@alanmoo This looks fine, doesn't seem like anything fancy (just a regular boilerplate view). I'll try to run some more in-depth tests on it later today (or tomorrow) depending on when I finish my homework :smiley:

**Comment by alanmoo** [comment]
I'm mainly curious if I've added too much anywhere, I was doing a lot of copying/pasting just to get stuff to work, not sure if I went overboard though I tried to take out anything I thought wasn't necessary.

**Comment by gvn** [comment]
Seems to work! R+

**Pull request merged**
