### PR TITLE
Hook up sharing intent

### PR DESCRIPTION
**Pull request by thisandagain**
Resolves GH-1713

/cc @secretrobotron @xmatthewx

### CODE REVIEW

**Comment by thisandagain** [comment]
@gvn @Pomax R?

**Comment by secretrobotron** [comment]
Nice :+1: Just tried it. Works well :).
Do we have a bug for deeplinking beta.webmaker.org/projects/XXX?

**Comment by thisandagain** [comment]
Adding now. Thanks @secretrobotron

**Comment by thisandagain** [comment]
https://github.com/mozilla/webmaker-desktop/issues/69

**Comment by gvn** [comment]
I don't know from Java, but the patch WFM on device! R+

**Pull request merged**
