### PR TITLE
Extract config variables from strings.xml

### PR DESCRIPTION
**Pull request by alicoding**
Extracting these to its own config file, so we can use strings.xml for localization instead.

### CODE REVIEW

**Comment by alicoding** [comment]
@k88hudson R?

**Comment by ryanw-se** [comment]
This change would break Google Analytics support, I originally put them in strings.xml because those values needed to be referenced in the code itself. See, https://github.com/mozilla/webmaker-android/blob/develop/app/src/main/java/org/mozilla/webmaker/WebmakerApplication.java#L32

**Comment by alicoding** [comment]
@k88hudson I also added all translation files into this patch as well :)

**Comment by k88hudson** [comment]
@alicoding R+

**Pull request merged**
