### PR TITLE
Crosswalk Impl & Notes

### PR DESCRIPTION
**Pull request by ryanw-se**
Crosswalk implementation for Android has been completed, its a full conversion from the old WebView. Because we have switched over to Crosswalk, some previously written JavaScript functionality will be broken by this update. These will need to be addressed before this can be accepted, as it essentially breaks the entire app.

@thisandagain and @k88hudson are looking into the JavaScript functionality that broke during the conversion, once that's completed and fixed this should be good to merge!

### CODE REVIEW

**Comment by ryanw-se** [comment]
@thisandagain We will probably need to have a discussion sometime tomorrow in IRC about this, so far with a few patches I've converted WebmakerWebView over to crosswalk and a lot of things have broken on the Javascript end.

**Comment by thisandagain** [comment]
@ryanw-se Sounds good! Talk tomorrow. Want to send along a "WIP" (work-in-progress) pull request so I can see what you are running into?

**Comment by thisandagain** [comment]
@ryanw-se Sounds good!

**Comment by thisandagain** [comment]
Merged! :smile: :cake: :cat: :boom:

**Pull request merged**
