### PR TITLE
Hook up 'play' activity. Re GH-1640

### PR DESCRIPTION
**Pull request by thisandagain**

### CODE REVIEW

**Comment by gvn** [comment]
Looks like you still need to add the prop to Project to indicate play mode.

See: https://github.com/mozilla/webmaker-android/pull/1901/files#diff-02fce5293d9817377f211ad1dde7633dR62

**Comment by thisandagain** [comment]
This gives you `mode: play` on the router mixin as per https://github.com/mozilla/webmaker-android/blob/develop/README.md#router

**Comment by gvn** [comment]
Ok cool. Is there a web route for this or can you only access this view on device?

**Comment by thisandagain** [comment]
It's just linked to the "Project" view from your PR.

**Comment by gvn** [comment]
Ok, I'm seeing it via remote inspector. I wonder if we should add `mode: "edit"` for edit mode.

**Comment by thisandagain** [comment]
Ok. All set.

**Pull request merged**
